### ISSUE TITLE
Feature Request - add a way to send &MEMO parameter over MQTT with this package

### ISSUE THREAD

**Issue by TaeKwonBow** [elad-bar/ha-blueiris#110]
Now that BI is integrating most of the logic of deepstack, it would be awesome if we could pipe this in to home assistant natively with this HA / Blue Iris package

**Comment by JOHLC** [comment]
That would be cool to do natively with this component without having to make a separate MQTT sensor as I am doing now. 

Currently have the camera's mqtt alert configured as: 
On alert:
```
Topic: BlueIris/&CAM/Status
Payload: {"type": "&TYPE", "trigger": "ON", "message": "&NAME motion &MEMO at %X", "memo": "&MEMO" }
```
On reset:
```
Topic: BlueIris/&CAM/Status
Payload: {"type": "&TYPE", "trigger": "OFF", "message": "&NAME motion &MEMO at %X", "memo": "&MEMO" }
```

This gives me the following result in MQTT: 
![image](https://user-images.githubusercontent.com/63735432/120930745-958b0780-c6bc-11eb-856a-b64d02e45b22.png)

I then create an MQTT sensor:
```
sensor:
  - platform: mqtt
    name: "BlueIris Front Door object"
    state_topic: "BlueIris/Livingroom/Status"
    value_template: "{{ value_json.memo }}"
    unique_id: "BlueIrisFrontDoorobject62021"
    icon: mdi:face-recognition
```

Which gives me:
![image](https://user-images.githubusercontent.com/63735432/120932489-fec24900-c6c3-11eb-8481-5aedd9224851.png)
