### ISSUE TITLE
All cameras stopped working with latest update.

### ISSUE THREAD

**Issue by mjoshd** [elad-bar/ha-blueiris#16]
@elad-bar  Please help!
I just updated to the latest code here and all cameras from this custom component have ceased providing video in Home Assistant. Not sure if it matters but I'm on Home Assistant 0.100.1

```text
Latest commit: 897d1dd
Changed camera to work with original GenericCamera
```
It appears this is now utilizing some form of the `stream:` component as there are new controls at the bottom of the window when a camera is opened which did not appear previously. The issue is that the stream never starts, I just get a spinning circle and blank window.

The `camera.entity` pictures do still update periodically so there is still data passing through. They also now have tokenized access to their still-images. 
Attributes for one of my cameras from this custom component:
```text
access_token: b085b4f00f83ff9b2fbff3d2c8c5bed2133d3d7c44240f6a1d2a3b9fc1340b93
friendly_name: C2 Pro
entity_picture: /api/camera_proxy/camera.c2_pro?token=b085b4f00f83ff9b2fbff3d2c8c5bed2133d3d7c44240f6a1d2a3b9fc1340b93
supported_features: 2
```

Please let me know if there is anything I can to do assist or testing/debugging that will help to resolve the issue.

**Comment by elad-bar** [comment]
Hi, fix was to support the generic camera after v0.100, can you provide more details from the logs?

**Comment by mjoshd** [comment]
Hi, 

I enabled 
```yaml
logger:
  default: warning
  logs:
    homeassistant.components.stream: debug
```

and the only thing that appears in the logs when clicking on a camera is 

```text
2019-10-11 17:34:54 INFO (MainThread) [homeassistant.components.stream] Started stream: http://USERNAME:PASSWORD@192.168.1.11:81/livestream.htm?cam=c2Pro
```
where 
USERNAME: username from custom component config
PASSWORD: password from custom component config

No errors are generated however the video never starts either... just a spinning circle on a blank background. To be sure, I let it sit for over two minutes... that stream wasn't going to display. 

As a test, I set up the same camera as a generic camera and used the rtsp feed and still image url of the camera:
```yaml
- platform: generic
  name: "c2Pro generic"
  still_image_url: !secret still_image_url_c2pro
  stream_source: !secret stream_source_c2pro
```
and it begins the video after only 3-5 seconds of the spinning circle.
Then I tried again using the onvif configuration with the same camera:
```yaml
- platform: onvif
  name: "c2Pro onvif"
  host: !secret c2pro_ip
  username: !secret onvif_c2pro_user
  password: !secret onvif_c2pro_pass
  port: 8000
```
and got the same result.. video starts after 3-5 seconds of spinning circle.

To be honest, the previous implementation where it used the mjpeg stream from Blue Iris gave excellent results and lightning fast playback by comparison. Even though it was unable to directly cast using the `stream:` component, it actually provided a much better experience (no delay to begin, no buffering, and no compounding latency) compared to what the official `stream:` component provides. 

I'm not sure what other logging to enable in order to assist. If there is anything else I can provide please do not hesitate to ask.

**Comment by mjoshd** [comment]
I tried a few other stream urls/configurations and was finally able to get the following to work:

Blue Iris mjpg (starts instantly and plays smooth but not compatible with HA `stream:` component) 
```yaml
- platform: mjpeg 
  mjpeg_url: "http://{username}:{password}@{bi_address:port}/mjpg/{cam-short-name}/video.mjpg"
  name: "HA Friendly Name"
```

Ffmpeg - uses Blue Iris m3u8 (compatible with HA `stream:` component but nowhere near as smooth as mjpg implementation of the same Blue Iris camera) 
```yaml
- platform: ffmpeg 
  input: "http://{username}:{password}@{bi_host}:{bi_port}/h264/{cam_short_name}/temp.m3u8"
  name: "HA Friendly Name"
```
and Generic - also uses Blue Iris m3u8; same caveats.
```yaml
- platform: generic
  still_image_url: "http://{username}:{password}@{bi_host}:{bi_port}/image/{cam_short_name}"
  stream_source: "http://{username}:{password}@{bi_host}:{bi_port}/h264/{cam_short_name}/temp.m3u8"
  name: "HA Friendly Name"
```

**Comment by mjoshd** [comment]
Eureka!!
After some more digging, I think we are again at the mercy of the URL construction...

Pasting the URL which will not play a stream into a Chrome tab results in a black screen with a large white play button in the middle. After the play button is clicked, the stream starts and seems to work just fine.

Home Assistant does not present this play button so that would explain why the stream can never be started. I believe if you change the url construction from
```text
http://{username}:{password}@{bi_host}:{bi_port}/livestream.htm?cam={cam_short_name}
```
to
```text
http://{username}:{password}@{bi_host}:{bi_port}/h264/{cam_short_name}/temp.m3u8
```
then it will start to work without issue (aside from the previously mentioned delay to begin playback, frequent buffering, and compounding latency which seem to come hand-in-hand with use of the `stream:` component).

Hopefully this helps 😄

**Comment by elad-bar** [comment]
checked it more deeply, the reason why the stream is not working with the component is basically because HA creates websocket for each of the camera, which overloads the instance running the BlueIris.

the fix for it is bit more complex than changing the URL (which I added anyway), 
to fix it the stream_source should be changed to direct connection to the camera - the URL needed to be extracted from BlueIris API as the original URL of the camera.
that will create small load on each of the camera but the BlueIris will be not get overloaded.

the behaviour I saw was that on the BlueIris got to ~99% which led to slow responses from the server, I'm running it on 8 core cpu with cuda.

you can take the latest commit and use for now the ```media_player.media_play``` service by running ```blueiris.generate_advanced_configurations``` to create all the components - input_options of all media players and camera and a script that calls ```media_player.media_play```

**Comment by mjoshd** [comment]
I tried the newest code (commit 5c44f69) and the issue is still there. I added more logging and found some other issues as well with the way the camera is created. For example, the video refuses to appear without the `USERNAME:PASSWORD@` inside the stream_url string. 

I'm working on another PR and will submit it shortly. Hopefully the info below is helpful. 

Logging used:
```yaml
logger:
  default: warning
  logs:
    homeassistant.components.stream: debug
    custom_components.blueiris: debug
```

Both the still_image url and the stream_source are still being based off of the Blue Iris server IP and not that of the individual cameras. The actual IP/username/password of the camera is not found anywhere in the logs.
The following is and excerpt from the logs; I'm replacing the Blue Iris username as "USERNAME" and password as "PASSWORD"; all other details (names, ids, IP addresses, etc are intact). 

192.168.11.11 is the Blue Iris server's IP and is what is used in all URLs.
192.168.21.5 is the C2 Pro's IP and is never referenced (it is on a separate VLAN).

I'm only including the details pertaining to the C2 Pro camera.. otherwise this would be a very long post.
```yaml
2019-10-13 08:41:47 DEBUG (SyncWorker_1) [custom_components.blueiris.blue_iris_data] Blue Iris camera loaded, details: {'id': 'c2ProResized', 'name': 'C2 Pro', 'room': 'Basement', 'still_image_url': Template("http://192.168.11.11:81/image/c2ProResized?q=100&s=100"), 'stream_source': 'http://192.168.11.11:81/h264/c2ProResized/temp.m3u8', 'username': 'USERNAME', 'password': 'PASSWORD'}
...
2019-10-13 08:41:47 DEBUG (SyncWorker_1) [custom_components.blueiris.blue_iris_api] BlueIrisData initialization with following configuration: base_url: http://192.168.11.11:81, username: USERNAME, password: PASSWORD
...
2019-10-13 08:41:48 DEBUG (MainThread) [custom_components.blueiris.binary_sensor] Processing new camera[c2ProResized]: {'id': 'c2ProResized', 'name': 'C2 Pro', 'room': 'Basement', 'still_image_url': Template("http://192.168.11.11:81/image/c2ProResized?q=100&s=100"), 'stream_source': 'http://192.168.11.11:81/h264/c2ProResized/temp.m3u8', 'username': 'USERNAME', 'password': 'PASSWORD'}
2019-10-13 08:41:48 DEBUG (MainThread) [custom_components.blueiris.binary_sensor] Blue Iris Binary Sensor created: <Entity C2 Pro motion: off>, state_topic: BlueIris/c2ProResized/MOTION_A
2019-10-13 08:41:48 DEBUG (MainThread) [custom_components.blueiris.binary_sensor] Blue Iris Binary Sensor created: <Entity C2 Pro audio: off>, state_topic: BlueIris/c2ProResized/AUDIO
2019-10-13 08:41:48 DEBUG (MainThread) [custom_components.blueiris.binary_sensor] Blue Iris Binary Sensor created: <Entity C2 Pro external: off>, state_topic: BlueIris/c2ProResized/EXTERNAL
2019-10-13 08:41:48 DEBUG (MainThread) [custom_components.blueiris.binary_sensor] Blue Iris Binary Sensor created: <Entity C2 Pro watchdog: on>, state_topic: BlueIris/c2ProResized/WATCHDOG
...
2019-10-13 08:41:48 INFO (MainThread) [custom_components.blueiris.camera] Processing new camera: c2ProResized
2019-10-13 08:41:48 INFO (MainThread) [custom_components.blueiris.camera] Creating camera: {'name': 'C2 Pro', 'still_image_url': Template("http://192.168.11.11:81/image/c2ProResized?q=100&s=100"), 'stream_source': 'http://192.168.11.11:81/h264/c2ProResized/temp.m3u8', 'limit_refetch_to_url_change': False, 'framerate': 2, 'content_type': 'image/jpeg', 'verify_ssl': False, 'username': 'USERNAME', 'password': 'PASSWORD', 'authentication': 'basic'}
2019-10-13 08:41:48 INFO (MainThread) [custom_components.blueiris.camera] Camera created: <Entity C2 Pro: idle>
```
