### ISSUE TITLE
FEATURE REQUEST: Control Camera Motion (On/Off)

### ISSUE THREAD

**Issue by RJ-Make** [elad-bar/ha-blueiris#164]
An entity to switch a camera's motion (Trigger Option) on or off. (and to retrieve its current status)

**Comment by kramttocs** [comment]
I like this idea. Will look into it.

**Comment by RJ-Make** [comment]
Any movement on this?

**Comment by kramttocs** [comment]
Sorry, no. I haven't had luck adding a new entity especially per camera.

BI has a camconfig command with motion having the definition of: true/false, enable/disable the motion detector for the currently effective profile

So that should be able to be used.

**Comment by RJ-Make** [comment]
Ok, Thanks! I figured out how to achieve this is yesterday with command_line. A bit of work for a single functions but sometime you have to do what you have to do? :-)

For others

In my config yaml
```
switch:
  - platform: command_line
    switches:
      inside_rear_camera_motion:
        unique_id: '12345irlcameramotion'
        command_on: !secret BI_IR1_Motion_On
        command_off: !secret BI_IR1_Motion_Off
```
Secrets
```
BI_IR1_Motion_On: "curl -k 'http://192.168.1.26:81/admin?camera=IR1&motion=1&user=USERNAME&pw=PASSWORD'"
BI_IR1_Motion_Off: "curl -k 'http://192.168.1.26:81/admin?camera=IR1&motion=0&user=USERNAME&pw=PASSWORD'"
```
