### ISSUE TITLE
Streams limited to around 5fps

### ISSUE THREAD

**Issue by craigueh** [elad-bar/ha-blueiris#83]
It seems that the cameras imported into Homeassistant are limited to a very low frame rate, around 5fps.
I've played with every setting I can find in the Blueiris backend but nothing seems to change it. Viewing cameras in the BI Windows app or via web browser all show 30fps but not Homeassistant.

Update. I've discovered that the h264 stream doesn't seem to be working and the addon seems to fall back to mjpeg. However, the mjpeg stream is somehow generating about 200Mbps traffic when streaming from BlueIris server.
Not sure what's going on here at all...

**Comment by elad-bar** [comment]
the component is generating the basic camera component, is it working for you better in case you are configuring all the cameras manually?

thanks

**Comment by elad-bar** [comment]
@craigueh any update?

**Comment by lsochanowski** [comment]
i have same issue and i can do some debuging but how to create cameras manualy?

**Comment by mjoshd** [comment]
@craigueh @lsochanowski, 
Hopefully these examples can help get you on the right track for testing manually created cameras.

@elad-bar, 
I would be happy to help with discovering the root cause.. I am affected by it as well but should not be. Both BI & HA are running on bare-metal with plenty of horse-power/resources available but the streams created by this integration still display at a very low fps rate compared to the same BI camera via mjpeg stream. Just let me know what info you need.

```yaml
#####################
# ### Blue Iris mjpeg (plays instantly & smoothly but not compatible with HA Stream service) 
#####################
# - platform: mjpeg 
#   mjpeg_url: "http://{username}:{password}@{bi_address:port}/mjpg/{cam-short-name}/video.mjpg"
#   name: "HA Name"
#####################
- platform: mjpeg 
  mjpeg_url: "http://BiAdminHA:sup3rS3kr3t@192.168.1.23:81/mjpg/dahua/video.mjpg"
  name: "Dahua MJPEG"
#####################
#####################
### Blue Iris m3u8 (compatible with HA Stream service but incurs 10+ sec delay due to HLS streaming) 
#####################
# - platform: ffmpeg 
#   input: "http://{username}:{password}@{bi_address:port}/h264/{cam_short_name}/temp.m3u8"
#   name: "HA Name"
#####################
- platform: ffmpeg 
  input: "http://BiAdminHA:sup3rS3kr3t@192.168.1.23:81/h264/dahua/temp.m3u8"
  name: "name: "Dahua FFMPEG"
#####################
#####################
```
